package report

import (
	"fmt"
	"path/filepath"
	"time"

	"github.com/johan-larp/agentsearch/internal/models"
	"github.com/unidoc/unioffice/color"
	"github.com/unidoc/unioffice/document"
)

// DOCXReport генерирует формальный Word-документ.
type DOCXReport struct{}

func NewDOCXReport() *DOCXReport {
	return &DOCXReport{}
}

func (d *DOCXReport) Generate(target string, results []models.Result, duration time.Duration) (string, error) {
	summary := BuildSummary(target, results, duration)
	path := filepath.Join("output", fmt.Sprintf("%s_report.docx", sanitizeFilename(target)))

	doc := document.New()

	// Заголовок
	title := doc.AddParagraph()
	titleRun := title.AddRun()
	titleRun.AddText("AgentSearch OSINT Report")
	titleRun.Properties().SetBold(true)
	titleRun.Properties().SetSize(28)

	// Мета-информация
	addMeta(doc, "Target:", target)
	addMeta(doc, "Generated:", time.Now().Format("2006-01-02 15:04:05"))
	addMeta(doc, "Duration:", duration.Round(time.Second).String())
	doc.AddParagraph()

	// Сводка
	h2 := doc.AddParagraph()
	h2Run := h2.AddRun()
	h2Run.AddText("Summary")
	h2Run.Properties().SetBold(true)
	h2Run.Properties().SetSize(18)

	addBullet(doc, fmt.Sprintf("Total checks: %d", summary.Total))
	addBullet(doc, fmt.Sprintf("Found: %d", summary.Found))
	addBullet(doc, fmt.Sprintf("Not Found: %d", summary.NotFound))
	addBullet(doc, fmt.Sprintf("Blocked by WAF: %d", summary.Blocked))
	addBullet(doc, fmt.Sprintf("Errors: %d", summary.Errors))
	doc.AddParagraph()

	// Found profiles
	if summary.Found > 0 {
		h3 := doc.AddParagraph()
		h3Run := h3.AddRun()
		h3Run.AddText("Found Profiles")
		h3Run.Properties().SetBold(true)
		h3Run.Properties().SetSize(18)

		for _, r := range results {
			if r.Status == models.StatusFound {
				p := doc.AddParagraph()
				p.AddRun().AddText(fmt.Sprintf("%s — %d%% confidence", r.SiteName, r.Confidence))
				p2 := doc.AddParagraph()
				p2Run := p2.AddRun()
				p2Run.AddText(r.URL)
				c := color.FromHex("0563C1")
				p2Run.Properties().SetColor(c)
			}
		}
	}

	// Blocked
	if summary.Blocked > 0 {
		h4 := doc.AddParagraph()
		h4Run := h4.AddRun()
		h4Run.AddText("Blocked by WAF")
		h4Run.Properties().SetBold(true)
		h4Run.Properties().SetSize(18)

		for _, r := range results {
			if r.Status == models.StatusBlocked {
				doc.AddParagraph().AddRun().AddText(fmt.Sprintf("%s: %s", r.SiteName, r.URL))
			}
		}
	}

	// Errors
	if summary.Errors > 0 {
		h5 := doc.AddParagraph()
		h5Run := h5.AddRun()
		h5Run.AddText("Errors")
		h5Run.Properties().SetBold(true)
		h5Run.Properties().SetSize(18)

		for _, r := range results {
			if r.Status == models.StatusError {
				p := doc.AddParagraph()
				run := p.AddRun()
				run.AddText(fmt.Sprintf("%s: %s", r.SiteName, r.Error))
				c := color.FromHex("C00000")
				run.Properties().SetColor(c)
			}
		}
	}

	// Footer
	doc.AddParagraph()
	footer := doc.AddParagraph()
	footerRun := footer.AddRun()
	footerRun.AddText("Report generated by AgentSearch")
	footerRun.Properties().SetSize(9)
	c := color.FromHex("666666")
	footerRun.Properties().SetColor(c)

	if err := doc.SaveToFile(path); err != nil {
		return "", fmt.Errorf("save docx: %w", err)
	}
	return path, nil
}

func addMeta(doc *document.Document, label, value string) {
	p := doc.AddParagraph()
	p.AddRun().AddText(label + " ")
	run := p.AddRun()
	run.AddText(value)
	run.Properties().SetBold(true)
}

func addBullet(doc *document.Document, text string) {
	p := doc.AddParagraph()
	p.SetStyle("ListParagraph")
	p.AddRun().AddText(text)
}
